# Generated by Django 3.1.3 on 2021-01-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='f_size',
        ),
        migrations.RemoveField(
            model_name='post',
            name='f_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='post',
            name='samp_freq',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
